version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: my_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - teste-anac

  adminer:
    image: adminer
    container_name: adminer_web
    restart: always
    ports:
      - "8080:8080"
    networks:
      - teste-anac

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_container
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@postgres:5432/mydatabase"
    volumes:
      - .:/app
    #command: ["python", "import.py"]
    networks:
      - teste-anac

volumes:
  postgres_data:
    driver: local

networks:
  teste-anac:
